gb.api.endpoint.base-uri: 'localhost:8080'
gb.api.endpoint.external-uri: 'localhost:8081'

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/gb_shop'
    username: 'geek'
    password: 'geek'
  artemis:
    password: 'simetraehcapa'
    user: 'artemis'

jwt:
  token:
    expired: 86_400_000
    secret: 'jwtsecret'
